using System;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using Plugify;

// Generated from s2sdk.pplugin (group: main)

namespace s2sdk {
#pragma warning disable CS0649

	internal static unsafe partial class s2sdk {

	}

	/// <summary>
	/// Static utility class for MEthodsUtils
	/// </summary>
	internal static unsafe class MEthodsUtils
	{
		/// <summary>
		/// Returns the maximum number of clients that can connect to the server.
		/// </summary>
		/// <returns>The maximum client count, or -1 if global variables are not initialized.</returns>
		public static int GetMaxClients()
		{
			return s2sdk.GetMaxClients();
		}

	}

	/// <summary>
	/// RAII wrapper for KeyValues handle.
	/// </summary>
	internal sealed unsafe class KeyValues : SafeHandle
	{
		/// <summary>
		/// Creates a new KeyValues instance
		/// </summary>
		/// <param name="setName">The name to assign to this KeyValues instance</param>
		public KeyValues(string setName) : this(s2sdk.Kv1Create(setName), Ownership.Owned)
		{
		}

		/// <summary>
		/// Internal constructor for creating KeyValues from existing handle
		/// </summary>
		private KeyValues(nint handle, Ownership ownership) : base(handle, ownsHandle: ownership == Ownership.Owned)
		{
		}

		/// <summary>
		/// Releases the handle (called automatically by SafeHandle)
		/// </summary>
		protected override bool ReleaseHandle()
		{
			s2sdk.Kv1Destroy(handle);
			return true;
		}

		/// <summary>
		/// Checks if the KeyValues has a valid handle
		/// </summary>
		public override bool IsInvalid => handle == nint.Zero;

		/// <summary>
		/// Gets the underlying handle
		/// </summary>
		public nint Handle => (nint)handle;

		/// <summary>
		/// Checks if the handle is valid
		/// </summary>
		public bool IsValid => handle != nint.Zero;

		/// <summary>
		/// Gets the underlying handle
		/// </summary>
		public nint Get() => (nint)handle;

		/// <summary>
		/// Releases ownership of the handle and returns it
		/// </summary>
		public nint Release()
		{
			var h = handle;
			SetHandleAsInvalid();
			return h;
		}

		/// <summary>
		/// Disposes the handle
		/// </summary>
		public void Reset()
		{
			Dispose();
		}

		/// <summary>
		/// Gets the section name of a KeyValues instance
		/// </summary>
		/// <returns>The name of the KeyValues section</returns>
		public string GetName()
		{
			ObjectDisposedException.ThrowIf(!IsValid, this);
			bool success = false;
			DangerousAddRef(ref success);
			try
			{
				return s2sdk.Kv1GetName(handle);
			}
			finally
			{
				if (success) DangerousRelease();
			}
		}

		/// <summary>
		/// Sets the section name of a KeyValues instance
		/// </summary>
		/// <param name="name">The new name to assign to this KeyValues section</param>
		public void SetName(string name)
		{
			ObjectDisposedException.ThrowIf(!IsValid, this);
			bool success = false;
			DangerousAddRef(ref success);
			try
			{
				s2sdk.Kv1SetName(handle, name);
			}
			finally
			{
				if (success) DangerousRelease();
			}
		}

		/// <summary>
		/// Finds a key by name
		/// </summary>
		/// <param name="keyName">The name of the key to find</param>
		/// <returns>Pointer to the found KeyValues subkey, or NULL if not found</returns>
		public KeyValues FindKey(string keyName)
		{
			ObjectDisposedException.ThrowIf(!IsValid, this);
			bool success = false;
			DangerousAddRef(ref success);
			try
			{
				return new KeyValues(s2sdk.Kv1FindKey(handle, keyName), Ownership.Borrowed);
			}
			finally
			{
				if (success) DangerousRelease();
			}
		}

		/// <summary>
		/// Creates a new subkey with the specified name
		/// </summary>
		/// <param name="keyName">The name for the new key</param>
		/// <returns>Pointer to the newly created KeyValues subkey</returns>
		public KeyValues CreateKey(string keyName)
		{
			ObjectDisposedException.ThrowIf(!IsValid, this);
			bool success = false;
			DangerousAddRef(ref success);
			try
			{
				return new KeyValues(s2sdk.Kv1CreateKey(handle, keyName), Ownership.Borrowed);
			}
			finally
			{
				if (success) DangerousRelease();
			}
		}

		/// <summary>
		/// Creates a new subkey with an autogenerated name
		/// </summary>
		/// <returns>Pointer to the newly created KeyValues subkey</returns>
		public KeyValues CreateNewKey()
		{
			ObjectDisposedException.ThrowIf(!IsValid, this);
			bool success = false;
			DangerousAddRef(ref success);
			try
			{
				return new KeyValues(s2sdk.Kv1CreateNewKey(handle), Ownership.Borrowed);
			}
			finally
			{
				if (success) DangerousRelease();
			}
		}

		/// <summary>
		/// Adds a subkey to this KeyValues instance
		/// </summary>
		/// <param name="subKey">Pointer to the KeyValues object to add as a child</param>
		public void AddSubKey(KeyValues subKey)
		{
			ObjectDisposedException.ThrowIf(!IsValid, this);
			bool success = false;
			DangerousAddRef(ref success);
			try
			{
				s2sdk.Kv1AddSubKey(handle, subKey.Release());
			}
			finally
			{
				if (success) DangerousRelease();
			}
		}

		/// <summary>
		/// Gets the first subkey in the list
		/// </summary>
		/// <returns>Pointer to the first subkey, or NULL if there are no children</returns>
		public KeyValues GetFirstSubKey()
		{
			ObjectDisposedException.ThrowIf(!IsValid, this);
			bool success = false;
			DangerousAddRef(ref success);
			try
			{
				return new KeyValues(s2sdk.Kv1GetFirstSubKey(handle), Ownership.Borrowed);
			}
			finally
			{
				if (success) DangerousRelease();
			}
		}

		/// <summary>
		/// Gets the next sibling key in the list
		/// </summary>
		/// <returns>Pointer to the next sibling key, or NULL if this is the last sibling</returns>
		public KeyValues GetNextKey()
		{
			ObjectDisposedException.ThrowIf(!IsValid, this);
			bool success = false;
			DangerousAddRef(ref success);
			try
			{
				return new KeyValues(s2sdk.Kv1GetNextKey(handle), Ownership.Borrowed);
			}
			finally
			{
				if (success) DangerousRelease();
			}
		}

		/// <summary>
		/// Gets a color value from a key
		/// </summary>
		/// <param name="keyName">The name of the key to retrieve the color from</param>
		/// <param name="defaultValue">The default color value to return if the key is not found</param>
		/// <returns>The color value as a 32-bit integer (RGBA)</returns>
		public int GetColor(string keyName, int defaultValue)
		{
			ObjectDisposedException.ThrowIf(!IsValid, this);
			bool success = false;
			DangerousAddRef(ref success);
			try
			{
				return s2sdk.Kv1GetColor(handle, keyName, defaultValue);
			}
			finally
			{
				if (success) DangerousRelease();
			}
		}

		/// <summary>
		/// Sets a color value for a key
		/// </summary>
		/// <param name="keyName">The name of the key to set the color for</param>
		/// <param name="value">The color value as a 32-bit integer (RGBA)</param>
		public void SetColor(string keyName, int value)
		{
			ObjectDisposedException.ThrowIf(!IsValid, this);
			bool success = false;
			DangerousAddRef(ref success);
			try
			{
				s2sdk.Kv1SetColor(handle, keyName, value);
			}
			finally
			{
				if (success) DangerousRelease();
			}
		}

		/// <summary>
		/// Gets an integer value from a key
		/// </summary>
		/// <param name="keyName">The name of the key to retrieve the integer from</param>
		/// <param name="defaultValue">The default value to return if the key is not found</param>
		/// <returns>The integer value associated with the key, or defaultValue if not found</returns>
		public int GetInt(string keyName, int defaultValue)
		{
			ObjectDisposedException.ThrowIf(!IsValid, this);
			bool success = false;
			DangerousAddRef(ref success);
			try
			{
				return s2sdk.Kv1GetInt(handle, keyName, defaultValue);
			}
			finally
			{
				if (success) DangerousRelease();
			}
		}

		/// <summary>
		/// Sets an integer value for a key
		/// </summary>
		/// <param name="keyName">The name of the key to set the integer for</param>
		/// <param name="value">The integer value to set</param>
		public void SetInt(string keyName, int value)
		{
			ObjectDisposedException.ThrowIf(!IsValid, this);
			bool success = false;
			DangerousAddRef(ref success);
			try
			{
				s2sdk.Kv1SetInt(handle, keyName, value);
			}
			finally
			{
				if (success) DangerousRelease();
			}
		}

		/// <summary>
		/// Gets a float value from a key
		/// </summary>
		/// <param name="keyName">The name of the key to retrieve the float from</param>
		/// <param name="defaultValue">The default value to return if the key is not found</param>
		/// <returns>The float value associated with the key, or defaultValue if not found</returns>
		public float GetFloat(string keyName, float defaultValue)
		{
			ObjectDisposedException.ThrowIf(!IsValid, this);
			bool success = false;
			DangerousAddRef(ref success);
			try
			{
				return s2sdk.Kv1GetFloat(handle, keyName, defaultValue);
			}
			finally
			{
				if (success) DangerousRelease();
			}
		}

		/// <summary>
		/// Sets a float value for a key
		/// </summary>
		/// <param name="keyName">The name of the key to set the float for</param>
		/// <param name="value">The float value to set</param>
		public void SetFloat(string keyName, float value)
		{
			ObjectDisposedException.ThrowIf(!IsValid, this);
			bool success = false;
			DangerousAddRef(ref success);
			try
			{
				s2sdk.Kv1SetFloat(handle, keyName, value);
			}
			finally
			{
				if (success) DangerousRelease();
			}
		}

		/// <summary>
		/// Gets a string value from a key
		/// </summary>
		/// <param name="keyName">The name of the key to retrieve the string from</param>
		/// <param name="defaultValue">The default string to return if the key is not found</param>
		/// <returns>The string value associated with the key, or defaultValue if not found</returns>
		public string GetString(string keyName, string defaultValue)
		{
			ObjectDisposedException.ThrowIf(!IsValid, this);
			bool success = false;
			DangerousAddRef(ref success);
			try
			{
				return s2sdk.Kv1GetString(handle, keyName, defaultValue);
			}
			finally
			{
				if (success) DangerousRelease();
			}
		}

		/// <summary>
		/// Sets a string value for a key
		/// </summary>
		/// <param name="keyName">The name of the key to set the string for</param>
		/// <param name="value">The string value to set</param>
		public void SetString(string keyName, string value)
		{
			ObjectDisposedException.ThrowIf(!IsValid, this);
			bool success = false;
			DangerousAddRef(ref success);
			try
			{
				s2sdk.Kv1SetString(handle, keyName, value);
			}
			finally
			{
				if (success) DangerousRelease();
			}
		}

		/// <summary>
		/// Gets a pointer value from a key
		/// </summary>
		/// <param name="keyName">The name of the key to retrieve the pointer from</param>
		/// <param name="defaultValue">The default pointer to return if the key is not found</param>
		/// <returns>The pointer value associated with the key, or defaultValue if not found</returns>
		public nint GetPtr(string keyName, nint defaultValue)
		{
			ObjectDisposedException.ThrowIf(!IsValid, this);
			bool success = false;
			DangerousAddRef(ref success);
			try
			{
				return s2sdk.Kv1GetPtr(handle, keyName, defaultValue);
			}
			finally
			{
				if (success) DangerousRelease();
			}
		}

		/// <summary>
		/// Sets a pointer value for a key
		/// </summary>
		/// <param name="keyName">The name of the key to set the pointer for</param>
		/// <param name="value">The pointer value to set</param>
		public void SetPtr(string keyName, nint value)
		{
			ObjectDisposedException.ThrowIf(!IsValid, this);
			bool success = false;
			DangerousAddRef(ref success);
			try
			{
				s2sdk.Kv1SetPtr(handle, keyName, value);
			}
			finally
			{
				if (success) DangerousRelease();
			}
		}

		/// <summary>
		/// Gets a boolean value from a key
		/// </summary>
		/// <param name="keyName">The name of the key to retrieve the boolean from</param>
		/// <param name="defaultValue">The default value to return if the key is not found</param>
		/// <returns>The boolean value associated with the key, or defaultValue if not found</returns>
		public Bool8 GetBool(string keyName, Bool8 defaultValue)
		{
			ObjectDisposedException.ThrowIf(!IsValid, this);
			bool success = false;
			DangerousAddRef(ref success);
			try
			{
				return s2sdk.Kv1GetBool(handle, keyName, defaultValue);
			}
			finally
			{
				if (success) DangerousRelease();
			}
		}

		/// <summary>
		/// Sets a boolean value for a key
		/// </summary>
		/// <param name="keyName">The name of the key to set the boolean for</param>
		/// <param name="value">The boolean value to set</param>
		public void SetBool(string keyName, Bool8 value)
		{
			ObjectDisposedException.ThrowIf(!IsValid, this);
			bool success = false;
			DangerousAddRef(ref success);
			try
			{
				s2sdk.Kv1SetBool(handle, keyName, value);
			}
			finally
			{
				if (success) DangerousRelease();
			}
		}

		/// <summary>
		/// Makes a deep copy of a KeyValues tree
		/// </summary>
		/// <returns>Pointer to the newly allocated copy of the KeyValues tree</returns>
		public KeyValues MakeCopy()
		{
			ObjectDisposedException.ThrowIf(!IsValid, this);
			bool success = false;
			DangerousAddRef(ref success);
			try
			{
				return new KeyValues(s2sdk.Kv1MakeCopy(handle), Ownership.Borrowed);
			}
			finally
			{
				if (success) DangerousRelease();
			}
		}

		/// <summary>
		/// Clears all subkeys and the current value
		/// </summary>
		public void Clear()
		{
			ObjectDisposedException.ThrowIf(!IsValid, this);
			bool success = false;
			DangerousAddRef(ref success);
			try
			{
				s2sdk.Kv1Clear(handle);
			}
			finally
			{
				if (success) DangerousRelease();
			}
		}

		/// <summary>
		/// Checks if a key exists and has no value or subkeys
		/// </summary>
		/// <param name="keyName">The name of the key to check</param>
		/// <returns>true if the key exists and is empty, false otherwise</returns>
		public Bool8 IsEmpty(string keyName)
		{
			ObjectDisposedException.ThrowIf(!IsValid, this);
			bool success = false;
			DangerousAddRef(ref success);
			try
			{
				return s2sdk.Kv1IsEmpty(handle, keyName);
			}
			finally
			{
				if (success) DangerousRelease();
			}
		}

	}

#pragma warning restore CS0649
}
